---
title: "Aquelarre estadístico"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style>
  .col2 {
    columns: 2 200px;         /* number of columns and width in pixels*/
    -webkit-columns: 2 200px; /* chrome, safari */
    -moz-columns: 2 200px;    /* firefox */
  }
  .col3 {
    columns: 3 100px;
    -webkit-columns: 3 100px;
    -moz-columns: 3 100px;
  }
</style>

Bienvenidos a la página de recursos para aprender estadística y programación a través del ambiente R. Esta página está diseñada para las asignaturas de "Modelación Estadística" e "Introducción a Métodos Multivariados" en la carrera de [Ciencias Ambientales](http://www.enesmorelia.unam.mx/index.php/oferta-academica/licenciaturas/licenciatura-en-ciencias-ambientales/#.XnKWkqgzYuE) y las asignaturas de [Estadística Aplicada a la Ecología I](http://www.ecologia.enesmorelia.unam.mx/pdf/27.pdf), [Estadística Aplicada a la Ecología II](http://www.ecologia.enesmorelia.unam.mx/pdf/34.pdf), [Ecología Teórica I](http://www.ecologia.enesmorelia.unam.mx/pdf/42.pdf), y [Ecología Informática](http://www.ecologia.enesmorelia.unam.mx/pdf/87.pdf) de la carrera de [Ecología](http://www.ecologia.enesmorelia.unam.mx/). Esta página también está destinada para los estudiantes del curso "Programación básica en R" en la Escuela Nacional de Estudios Superiores, unidad Morelia. En esta página conocerán el ambiente de R, los fundamentos básicos de análisis y programación, el marco conceptual y aplicaciones de distintos análisis estadísticos y matemáticos en las ciencias biológicas, sociales y económicas.

## Requisitos

La información de esta página está dirigida a todo el público. Es necesario que tengan nociones básicas de estadística. En este curso abordaremos problemáticas que van desde temas administrativos y de contabilidad, hasta biológicos y de manejo de recursos naturales. El objetivo es que el participante conozca el potencial que tienen la estadística y R en estas disciplinas.

## [Acerca de mi](about.html)

## Temario general
<div class = "col3">
1. Introducción a R
    + Historia
    + Interfaz
    + Operadores
        + Lógicos
        + Matemáticos
    + [Estructura básica de datos](est_bas.html)
        + [Vectores atómicos](est_bas.html#111_atómicos)
        + [Vectores listas](est_bas.html#112_listas)
    + [Estructura avanzada de datos](est_avz.html)
        + [Clase S3](est_avz.html#111_clase_s3)
          + [Atómicos](est_avz.html#1111_vectores_atómicos_s3)
          + [Listas](est_avz.html#1112_vectores_lista_s3)
        + [Clase S4](est_avz.html#112_clase_s4)
        + [Clase referencia](est_avz.html#113_clase_referencia)
2. Programación en R
    + Comandos básicos
        + Iteraciones
            + for
            + while
            + repeat
        + Funciones básicas
            + function
            + if
            + else
        + Funciones avanzadas
            + apply
            + sapply
            + lapply
            + tapply
    + Aplicaciones
        + Elaboración de algoritmos
        + Optimización
            + Código
            + Paralelización
        + Bases de datos
            + Fundamentos básicos de SQL
    + Paquetes
        + Elaboración de un paquete R
    + Proyectos
        + Individual
        + Grupales
        + Reporte web
        + Reporte pdf
3. Estadística
    + Estadistica descriptiva
        + Medidas
            + Tendencia central
                + Media
                + Mediana
                + Moda
            + Posición
                + Límites
                + Cuartiles
            + Dispersión
                + Varianza
                + Desviación estándar
                + Coeficiente de variación
        + Gráficas
            + Histograma
            + Boxplot
            + Barplot
            + Scatterplot
    + Estadística inferencial
        + Distribuciones de probabilidad
            + Binomial
            + Poisson
            + Normal
        + Estimadores
            + Error estándar
            + Intervalos de confianza
            + Tamaño de muestra
                + Con remuestreo
                + Sin remuestreo
        + Pruebas de hipótesis
            + Una media/proporción
            + Dos medias/proporciones
            + Análisis de varianza (ANOVA)
                + Una vía
                + Dos vías
                + Anidado
                + Medidas repetidas
            + Correlación
                + Pearson
                + Spearman
            + Modelos lineales
                + Regresión simple
                + Regresión múltiple
                    + Variables independientes
                    + Interacción de variables
                + Análisis de covarianza (ANCOVA)
              + Modelos lineales generalizados (GLM)
                + Gaussiano
                + Poisson
                + Binomial
                  + Presencia/ausencia
                  + Proporciones
              + Modelos aditivos generalizados (GAM)
</div>